spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:dbusers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sasa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

application:
  name: UsersApp
  version: 1.0.0
server:
  port: 8090

jwt:
  secret: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924



